/**
 * Generates documentation from the code registries so it cannot drift:
 *   docs/DATA-COLLECTION.md  - every dataset, its source operations, permissions and personal data
 *   docs/CONTROL-CATALOG.md  - every implemented control
 * Run `npm run docs:generate`. tests/generated-docs.test.ts fails if the files are stale.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { COLLECTOR_MODULES, TECHNOLOGY_LABELS } from '@adminsecops/core';
import { CONTROL_LIBRARY, CONTROL_LIBRARY_VERSION } from '@adminsecops/controls';
import { FRAMEWORKS, listDatasetDefinitions } from '@adminsecops/schemas';

const md = (text: string) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function dataCollectionDoc(): string {
  const datasets = listDatasetDefinitions();
  const lines: string[] = [
    '# Data collection',
    '',
    '<!-- Generated by scripts/generate-docs.ts from packages/schemas/src/datasets. Do not edit by hand. -->',
    '',
    'AdminSecOps collectors are **read-only**. They collect configuration metadata only, using',
    'the operations listed below, and write one evidence file per dataset. The engine strips any',
    'property that is not declared in the dataset schema and rejects files containing secret material.',
    '',
    '**Never collected:** passwords, password hashes, access or refresh tokens, private keys,',
    'authentication cookies, e-mail message bodies, Teams messages, SharePoint/OneDrive documents,',
    'LAPS passwords, client secret values or hints, security contact e-mail addresses, banned password lists.',
    '',
    '## Least-privilege access by module',
    '',
    '| Module | Recommended role | Notes |',
    '|---|---|---|',
    '| Entra | Global Reader (delegated Microsoft Graph read scopes) | `entra.onPremisesSynchronization` additionally requires Global Administrator or Hybrid Identity Administrator; without it the dataset is reported Unauthorized and dependent controls are Not assessed. |',
    '| M365 | Global Reader (SharePointTenantSettings.Read.All) | |',
    '| Exchange | View-Only Organization Management (or Global Reader) in Exchange Online | DNS lookups are public. |',
    '| Intune | Global Reader or Intune Read Only Operator | |',
    '| Azure | Reader on each subscription (or a management group) | Principal names need directory read access. |',
    '| AD / ADCS / GPO | Authenticated domain user | Optional domain controller registry settings require local administrator on DCs (`-IncludeDomainControllerSettings`). |',
    '| Windows | Local administrator on the assessed host | Collects the local host only. |',
    '',
    'Licence prerequisites are detected: when a feature is not licensed the dataset is reported',
    '`NotApplicable` and dependent controls are `NOT_APPLICABLE`, never `PASS`.',
    '',
    '## Personal data classes',
    '',
    '- **none** - configuration only.',
    '- **identifiers** - names, UPNs or account names of users, groups, devices or mailboxes.',
    '- **identifiers-and-activity** - identifiers plus activity metadata such as last sign-in time.',
    '',
    `## Datasets (${datasets.length})`,
    '',
  ];
  for (const module of COLLECTOR_MODULES) {
    const moduleSets = datasets.filter((d) => d.module === module);
    if (moduleSets.length === 0) continue;
    lines.push(`### ${module}`, '', '| Dataset | Description | Read operations | Permissions | Prerequisites | Personal data |', '|---|---|---|---|---|---|');
    for (const d of moduleSets) {
      lines.push(
        `| \`${d.id}\` | ${md(d.description)} | ${d.operations.map((o) => `\`${md(o)}\``).join('<br>')} | ${d.permissions.map(md).join('<br>')} | ${(d.prerequisites ?? []).map(md).join('<br>') || '-'} | ${d.personalData} |`,
      );
    }
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}

export function controlCatalogDoc(): string {
  const controls = [...CONTROL_LIBRARY].sort((a, b) => a.metadata.id.localeCompare(b.metadata.id));
  const lines: string[] = [
    '# Control catalog',
    '',
    '<!-- Generated by scripts/generate-docs.ts from packages/controls. Do not edit by hand. -->',
    '',
    `Control library version ${CONTROL_LIBRARY_VERSION}: **${controls.length} implemented controls**. Each has`,
    'tests, authoritative references, remediation, rollback and validation guidance. See',
    '[CONTROL-MODEL.md](CONTROL-MODEL.md) for the model and statuses.',
    '',
  ];
  const technologies = [...new Set(controls.map((c) => c.metadata.technology))];
  for (const tech of technologies) {
    const list = controls.filter((c) => c.metadata.technology === tech);
    lines.push(`## ${TECHNOLOGY_LABELS[tech]} (${list.length})`, '', '| ID | Title | Severity | Confidence | Evidence | Frameworks |', '|---|---|---|---|---|---|');
    for (const { metadata: m } of list) {
      const frameworks = m.frameworkMappings.map((f) => `${f.framework === 'NIST-800-53r5' ? 'NIST' : f.framework === 'MITRE-ATTACK' ? 'ATT&CK' : f.framework === 'CISA-SCuBA' ? 'SCuBA' : f.framework} ${f.id}`).join(', ');
      lines.push(`| ${m.id} | ${md(m.title)} | ${m.severity} | ${m.confidence} | ${m.requiredEvidence.map((e) => `\`${e}\``).join(', ')} | ${md(frameworks) || '-'} |`);
    }
    lines.push('');
  }
  lines.push('Framework abbreviations: ' + Object.entries(FRAMEWORKS).map(([k, v]) => `${k} = ${v}`).join('; ') + '.', '');
  return `${lines.join('\n')}\n`;
}

const docsDir = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'docs');
if (process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(path.join(docsDir, 'DATA-COLLECTION.md'), dataCollectionDoc());
  writeFileSync(path.join(docsDir, 'CONTROL-CATALOG.md'), controlCatalogDoc());
  process.stdout.write('Generated docs/DATA-COLLECTION.md and docs/CONTROL-CATALOG.md\n');
}
